### ISSUE TITLE
服务器部署启动失败

### ISSUE THREAD

**Issue by fjwnb** [gx304419380/ai-service#1]
楼主您好啊，我服务器去部署该的时候，普通启动项目，nohub java -jar 会一直报错Caused by: java.lang.UnsatisfiedLinkError: /root/.djl.ai/pytorch/1.9.1-cpu-linux-x86_64/libtorch_cpu.so: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /root/.djl.ai/pytorch/1.9.1-cpu-linux-x86_64/libtorch_cpu.so)，我centos是GLIBC_2.17，python3.8.1, pytorch1.91，能指教一下嘛，麻烦了，不会python但是想用ocr被环境搞得无语，windows10下您的项目是可以启动起来的。
pip3环境如下:
Package                Version
---------------------- ----------
astor                  0.8.1
certifi                2021.10.8
charset-normalizer     2.0.12
decorator              5.1.1
easyocr                1.4.1
gast                   0.3.3
idna                   3.3
imageio                2.9.0
networkx               2.7.1
numpy                  1.22.3
opencv-python          4.5.5.64
opencv-python-headless 4.5.4.60
packaging              21.3
paddlepaddle           2.0.0
Pillow                 8.2.0
pip                    22.0.4
protobuf               3.19.4
pyparsing              3.0.7
python-bidi            0.4.2
PyWavelets             1.3.0
PyYAML                 6.0
requests               2.27.1
scikit-image           0.19.2
scipy                  1.8.0
setuptools             41.2.0
six                    1.16.0
tifffile               2022.3.16
torch                  1.9.1+cpu
torchaudio             0.9.1
torchvision            0.10.1+cpu
typing_extensions      4.1.1
urllib3                1.26.9

启动时具体关键错误信息如下：
Caused by: java.lang.ExceptionInInitializerError: null
	at ai.djl.paddlepaddle.engine.PpEngine.newBaseManager(PpEngine.java:110) ~[paddlepaddle-engine-0.15.0.jar!/:na]
	at ai.djl.paddlepaddle.engine.PpEngine.newModel(PpEngine.java:92) ~[paddlepaddle-engine-0.15.0.jar!/:na]
	at ai.djl.Model.newInstance(Model.java:98) ~[api-0.15.0.jar!/:na]
	at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:187) ~[api-0.15.0.jar!/:na]
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:149) ~[api-0.15.0.jar!/:na]
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:166) ~[api-0.15.0.jar!/:na]
	at com.example.myocr.ocr.OcrService.init(OcrService.java:207) ~[classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.17.jar!/:5.3.17]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.17.jar!/:5.3.17]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.17.jar!/:5.3.17]
	... 40 common frames omitted
Caused by: ai.djl.engine.EngineException: Failed to load PyTorch native library
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:77) ~[pytorch-engine-0.15.0.jar!/:na]
	at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40) ~[pytorch-engine-0.15.0.jar!/:na]
	at ai.djl.engine.Engine.getEngine(Engine.java:177) ~[api-0.15.0.jar!/:na]
	at ai.djl.engine.Engine.getInstance(Engine.java:132) ~[api-0.15.0.jar!/:na]
	at ai.djl.paddlepaddle.engine.PpEngine.getAlternativeEngine(PpEngine.java:54) ~[paddlepaddle-engine-0.15.0.jar!/:na]
	at ai.djl.ndarray.BaseNDManager.getAlternativeManager(BaseNDManager.java:372) ~[api-0.15.0.jar!/:na]
	at ai.djl.paddlepaddle.engine.PpNDManager.<init>(PpNDManager.java:36) ~[paddlepaddle-engine-0.15.0.jar!/:na]
	at ai.djl.paddlepaddle.engine.PpNDManager.<init>(PpNDManager.java:28) ~[paddlepaddle-engine-0.15.0.jar!/:na]
	at ai.djl.paddlepaddle.engine.PpNDManager$SystemManager.<init>(PpNDManager.java:118) ~[paddlepaddle-engine-0.15.0.jar!/:na]
	at ai.djl.paddlepaddle.engine.PpNDManager.<clinit>(PpNDManager.java:30) ~[paddlepaddle-engine-0.15.0.jar!/:na]
	... 54 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /root/.djl.ai/pytorch/1.9.1-cpu-linux-x86_64/libtorch_cpu.so: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /root/.djl.ai/pytorch/1.9.1-cpu-linux-x86_64/libtorch_cpu.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_191]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[na:1.8.0_191]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[na:1.8.0_191]
	at java.lang.Runtime.load0(Runtime.java:809) ~[na:1.8.0_191]
	at java.lang.System.load(System.java:1086) ~[na:1.8.0_191]
	at ai.djl.pytorch.jni.LibUtils.loadNativeLibrary(LibUtils.java:328) ~[pytorch-engine-0.15.0.jar!/:na]
	at ai.djl.pytorch.jni.LibUtils.loadLibTorch(LibUtils.java:144) ~[pytorch-engine-0.15.0.jar!/:na]
	at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:72) ~[pytorch-engine-0.15.0.jar!/:na]
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:50) ~[pytorch-engine-0.15.0.jar!/:na]
	... 63 common frames omitted

**Comment by fjwnb** [comment]
> 看异常应该是linux下的pytorch动态结果但是找到相应的文件，我没有新拉了一个链接加载库：linux，里面打出来的jar包有比较需要的so文件，jar包大，3G，你可以尝试下来

麻烦您了，谢谢了，还是报错，Caused by: java.lang.UnsatisfiedLinkError: /root/.djl.ai/pytorch/1.10.0-20220111-cpu-linux-x86_64/libtorch_cpu.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /root/.djl.ai/pytorch/1.10.0-20220111-cpu-linux-x86_64/libtorch_cpu.so)，我再看看吧
